CREATE TABLE "CUSTOMFILE"
(
    "ID" NVARCHAR2(255) NOT NULL,
    "FILENAME" NVARCHAR2(255),
    "FILESIZE"     NUMBER(20),
    "FILEPATH" NVARCHAR2(255),
    "SEGMENTINDEX" NUMBER(11),
    "SEGMENTSIZE"  NUMBER(20),
    "SEGMENTTOTAL" NUMBER(11),
    "ISMERGE"      NUMBER(4),
    "ISST"         NUMBER(4),
    "FILEMD5" NVARCHAR2(255),
    "FILEKEY" NVARCHAR2(255),
    "UPLOADDATE"   DATE,
    "ISDELETE"     NUMBER(4),
    PRIMARY KEY ("ID")
);
CREATE INDEX "FILEKEY_INDEX"
    ON "CUSTOMFILE" ("FILEKEY");
CREATE INDEX "FILEMD5_INDEX"
    ON "CUSTOMFILE" ("FILEMD5");
COMMENT
ON COLUMN "CUSTOMFILE"."ID" IS '主键ID';
COMMENT
ON COLUMN "CUSTOMFILE"."FILENAME" IS '文件名';
COMMENT
ON COLUMN "CUSTOMFILE"."FILESIZE" IS '文件大小';
COMMENT
ON COLUMN "CUSTOMFILE"."FILEPATH" IS '文件路径';
COMMENT
ON COLUMN "CUSTOMFILE"."SEGMENTINDEX" IS '分片索引';
COMMENT
ON COLUMN "CUSTOMFILE"."SEGMENTSIZE" IS '分片大小';
COMMENT
ON COLUMN "CUSTOMFILE"."SEGMENTTOTAL" IS '分片总数';
COMMENT
ON COLUMN "CUSTOMFILE"."ISMERGE" IS '是否合并';
COMMENT
ON COLUMN "CUSTOMFILE"."ISST" IS '是否秒传';
COMMENT
ON COLUMN "CUSTOMFILE"."FILEMD5" IS 'MD5';
COMMENT
ON COLUMN "CUSTOMFILE"."FILEKEY" IS 'KEY';
COMMENT
ON COLUMN "CUSTOMFILE"."UPLOADDATE" IS '上传日期';
COMMENT
ON COLUMN "CUSTOMFILE"."ISDELETE" IS '是否删除';

